"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['url-open-handler.py']
DATA_FILES = ['handler']
OPTIONS = {
    'argv_emulation': True,
    'plist' : {
        'CFBundleDevelopmentRegion' : 'en',
        'NSPrincipalClass' : 'NSApplication',
        'NSAppleScriptEnabled' : 'YES',
        'LSUIElement' : 'YES',
        'CFBundleIdentifier' : 'org.irq0.custom_url_handler',
        'CFBundleURLTypes' : [{
                'CFBundleURLName' : 'eMail Message',
                'CFBundleURLSchemes' : [
                    'message',
                    'mailto',
                    ]
                }]
        }
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
